services:
  # BEAM Demo - Single container for easy demo experience
  beam-demo:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.demo
    container_name: beam-demo
    volumes:
      # Optional: Mount host directory to save demo results
      - ./demo_results:/app/data/demo_temp
    environment:
      - PYTHONPATH=/app/src
      - PYTHONUNBUFFERED=1
      - DOCKER_DEMO=true
    stdin_open: true
    tty: true
    command: ["python", "-c", "from beam.demo import run_demo; run_demo()"]

  # Alternative: Interactive shell for exploration
  beam-interactive:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.demo
    container_name: beam-interactive
    volumes:
      - ./demo_results:/app/data/demo_temp
    environment:
      - PYTHONPATH=/app/src
      - PYTHONUNBUFFERED=1
      - DOCKER_DEMO=true
    stdin_open: true
    tty: true
    command: ["/bin/bash"]
    profiles:
      - interactive

volumes:
  demo_results:
    driver: local
